apiVersion: v1
kind: ServiceAccount
metadata:
  name: kie-workbench-restart-tool-use-policy
  namespace: drools
  annotations:
    argocd.argoproj.io/sync-wave: "27"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kie-workbench-restart-tool-use-policy
  namespace: drools
  annotations:
    argocd.argoproj.io/sync-wave: "27"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["kie-workbench"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kie-workbench-restart-tool-use-policy
  namespace: drools
  annotations:
    argocd.argoproj.io/sync-wave: "27"
subjects:
  - kind: ServiceAccount
    name: kie-workbench-restart-tool-use-policy
    namespace: drools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kie-workbench-restart-tool-use-policy
