apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - maven-repo-config.yaml
  - register-container-config.yaml
  - register-container-job.yaml
  - workbench-import-config.yaml
  - workbench-import-job.yaml
