apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - maven-repo-config.yaml
  - register-container-config.yaml
  - register-container-job.yaml
  - kie-server-restart-postsync.yaml
  - kie-server-restart-rbac.yaml
  - kie-workbench-restart-postsync.yaml
  - kie-workbench-restart-rbac.yaml
  - workbench-import-config.yaml
  - workbench-import-job.yaml
  - vault-yugabyte-tool-use-policy.yaml
