apiVersion: v1
kind: ConfigMap
metadata:
  name: register-container-config-tool-use-policy
  namespace: drools
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  WORKBENCH_CONTROLLER_URL: "http://kie-workbench.drools.svc.cluster.local:8080/business-central/rest/controller"
  KIE_SERVER_ID: "auto"
  KIE_SERVER_ID_PREFIX: "kie-server-"
  CONTAINER_ID: "tool-use-policy"
  GROUP_ID: "com.dotcomrow.rules"
  ARTIFACT_ID: "tool-use-policy"
  VERSION: "1.0.129"
  CONTAINER_STATUS: "STARTED"
  LOG_HTTP: "true"
  LOG_HTTP_ONLY_ERRORS: "false"
  LOG_HTTP_BODY_MAX: "8000"
