apiVersion: v1
kind: ConfigMap
metadata:
  name: register-container-config-tool-use-policy
  namespace: drools
data:
  WORKBENCH_CONTROLLER_URL: "http://kie-workbench.drools.svc.cluster.local:8080/business-central/rest/controller"
  KIE_SERVER_ID: "kie-server"
  CONTAINER_ID: "tool-use-policy"
  GROUP_ID: "com.dotcomrow.rules"
  ARTIFACT_ID: "tool-use-policy"
  VERSION: "1.0.47"
  CONTAINER_STATUS: "STARTED"
