apiVersion: v1
kind: ConfigMap
metadata:
  name: workbench-import-config-tool-use-policy
  namespace: drools
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  WORKBENCH_BASE: "http://kie-workbench.drools.svc.cluster.local:8080/business-central"
  SPACE_NAME: "rules"
  SPACE_DESC: "Rules"
  DEFAULT_GROUP_ID: "com.dotcomrow.rules"
  REPO_NAME: "tool-use-policy"
  REPO_URL: "https://github.com/dotcomrow/drools-rule-app-tool-use-policy.git"
  REPO_BRANCH: "prod"
  REPO_VERSION: "1.0.171"
  VERSION_PREFIX: ""
  SPACE_WAIT_SECONDS: "300"
  SPACE_OWNER: ""
  HOLD_POD: "false"
  DEBUG_REST: "true"
