name: publish

on:
  push:
    branches:
      - main
      - prod

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Compute version
        run: echo "REVISION=1.0.$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        with:
          distribution: temurin
          java-version: "11"
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build and publish
        run: mvn -B -ntp -Drevision=$REVISION deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
